# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCanvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descri\xe7\xe3o')),
                ('icone', models.CharField(max_length=120, verbose_name='Descri\xe7\xe3o')),
                ('codigo_cor_hex', models.CharField(max_length=7, verbose_name='C\xf3digo Hexadecimal da Cor')),
            ],
            options={
                'verbose_name': 'Categorias do Canvas',
                'verbose_name_plural': 'Categorias do Canvas',
            },
        ),
        migrations.CreateModel(
            name='ItemCategoriaCanvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conte\xfado')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_cycle_canvas.CategoriaCanvas')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Canvas',
                'verbose_name_plural': 'Itens do Canvas',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='T\xedtulo')),
                ('pitch', models.CharField(max_length=120, verbose_name='Pitch')),
                ('indicacao_desempenho', models.PositiveIntegerField(choices=[(0, 'Verde'), (1, 'Amarelo'), (2, 'Vermelho')], verbose_name='Indica\xe7\xe3o Geral de Desempenho do Projeto')),
                ('data', models.DateField(auto_now_add=True)),
                ('local', models.CharField(max_length=120, verbose_name='Local')),
                ('patrocinador', models.CharField(max_length=120, verbose_name='Patrocinador')),
                ('cliente', models.CharField(max_length=120, verbose_name='Cliente')),
                ('gerente_projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gerente do Projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='VersaoProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='C\xf3digo')),
            ],
            options={
                'verbose_name': 'Vers\xe3o do Projeto',
                'verbose_name_plural': 'Vers\xf5es do Projeto',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='versao_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life_cycle_canvas.VersaoProjeto', verbose_name='Vers\xe3o'),
        ),
        migrations.AddField(
            model_name='itemcategoriacanvas',
            name='versao_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_cycle_canvas.VersaoProjeto'),
        ),
    ]
