# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life_cycle_canvas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='versao_atual',
        ),
        migrations.AddField(
            model_name='versaoprojeto',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life_cycle_canvas.Projeto', verbose_name='Projeto'),
        ),
    ]
