# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_cycle_canvas', '0002_auto_20180221_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacanvas',
            name='icone',
            field=models.CharField(max_length=120, verbose_name='\xcdcone'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='indicacao_desempenho',
            field=models.PositiveIntegerField(choices=[(0, 'Verde'), (1, 'Amarelo'), (2, 'Vermelho')], default=0, verbose_name='Indica\xe7\xe3o Geral de Desempenho do Projeto'),
        ),
    ]
