# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life_cycle_canvas', '0003_auto_20180222_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMudanca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.CharField(max_length=120, verbose_name='Solicita\xe7\xe3o')),
                ('solicitante', models.CharField(max_length=120, verbose_name='Solicitante')),
                ('origem', models.CharField(max_length=120, verbose_name='Origem')),
                ('parecer', models.CharField(max_length=120, verbose_name='Parecer')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Aprovada'), (1, 'Aprovada com replanejamento'), (2, 'Rejeitada')])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_avaliacao', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='itemcategoriacanvas',
            name='usuario_atualizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_atualizacao_item_canvas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcategoriacanvas',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro_item_canvas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pitch',
            field=models.CharField(max_length=120, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='versaoprojeto',
            name='codigo',
            field=models.PositiveIntegerField(verbose_name='C\xf3digo do Projeto'),
        ),
        migrations.AddField(
            model_name='solicitacaomudanca',
            name='item_mudanca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_cycle_canvas.ItemCategoriaCanvas'),
        ),
        migrations.AddField(
            model_name='solicitacaomudanca',
            name='usuario_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_avaliacao_solicitacao_mudanca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaomudanca',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro_solicitacao_mudanca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaomudanca',
            name='versao_anterior_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versao_anterior', to='life_cycle_canvas.VersaoProjeto'),
        ),
        migrations.AddField(
            model_name='solicitacaomudanca',
            name='versao_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nova_versao', to='life_cycle_canvas.VersaoProjeto'),
        ),
    ]
