# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life_cycle_canvas', '0004_auto_20180222_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaomudanca',
            options={'verbose_name': 'Solicita\xe7\xe3o de Mudan\xe7a', 'verbose_name_plural': 'Solicita\xe7\xf5es de Mudan\xe7a'},
        ),
        migrations.AlterField(
            model_name='solicitacaomudanca',
            name='item_mudanca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_cycle_canvas.ItemCategoriaCanvas', verbose_name='Item do Canvas'),
        ),
        migrations.AlterField(
            model_name='solicitacaomudanca',
            name='solicitacao',
            field=models.TextField(verbose_name='Solicita\xe7\xe3o'),
        ),
    ]
