# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life_cycle_canvas', '0005_auto_20180222_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategoriacanvas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcategoriacanvas',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_atualizacao_item_canvas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcategoriacanvas',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro_item_canvas', to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio'),
        ),
        migrations.AlterField(
            model_name='itemcategoriacanvas',
            name='versao_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_cycle_canvas.VersaoProjeto', verbose_name='Vers\xe3o do Projeto'),
        ),
    ]
